spring:
   profiles: dev  #开发环境
   application:
    name: woniucloud-provider
    
---

spring:
   profiles: test  #测试环境
   application:
    name: woniucloud-provider
    
---

spring:
   profiles: pro  #生产环境
   application:
    name: woniucloud-provider 
